name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./volunteer/pom.xml
          mvn clean package -f ./matching/pom.xml
          mvn clean package -f ./volunteering/pom.xml
          mvn clean package -f ./수혜기관/pom.xml
          mvn clean package -f ./mypage/pom.xml

      - name: Docker Build and push for Volunteer
        uses: docker/build-push-action@v4
        with:
          context: ./volunteer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/volunteer:latest
            ghcr.io/${{ github.repository }}/volunteer:${{ github.ref_name }}
            
      - name: Docker Build and push for Matching
        uses: docker/build-push-action@v4
        with:
          context: ./matching
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/matching:latest
            ghcr.io/${{ github.repository }}/matching:${{ github.ref_name }}
            
      - name: Docker Build and push for Volunteering
        uses: docker/build-push-action@v4
        with:
          context: ./volunteering
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/volunteering:latest
            ghcr.io/${{ github.repository }}/volunteering:${{ github.ref_name }}
            
      - name: Docker Build and push for 수혜기관
        uses: docker/build-push-action@v4
        with:
          context: ./수혜기관
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/수혜기관:latest
            ghcr.io/${{ github.repository }}/수혜기관:${{ github.ref_name }}
            
      - name: Docker Build and push for Mypage
        uses: docker/build-push-action@v4
        with:
          context: ./mypage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/mypage:latest
            ghcr.io/${{ github.repository }}/mypage:${{ github.ref_name }}
            
